from __future__ import annotations

import re
from typing import Any

from Schema import (
    Schema,
    SchemaField,
    SchemaMethod,
    SchemaParameter,
    SchemaType,
    SchemaUnion,
)


class OpenAPIParser:
    """
    Parse the OpenAPI document generated by tgbotspec into the project's
    intermediate Schema representation.

    Supported:

    - OpenAPI object schemas
    - enum schemas
    - arrays
    - primitive types
    - $ref
    - allOf
    - oneOf
    - anyOf
    - requestBody parameters
    - JSON request bodies
    - response result types
    - named unions expressed by oneOf/anyOf
    - named unions expressed in Telegram's description text

    Telegram currently has several schemas whose union semantics are
    represented in the description rather than OpenAPI oneOf/anyOf.

    Example:

        description:
          This object represents the content of a media message to be sent.
          It should be one of
          InputMediaAnimation
          InputMediaAudio
          InputMediaDocument
          InputMediaLivePhoto
          InputMediaPhoto
          InputMediaVideo

    Such schemas are converted into SchemaUnion objects with
    kind="polymorphic".
    """

    REF_PREFIX = "#/components/schemas/"

    # Telegram uses several natural-language forms to describe named
    # polymorphic base types. Keep these patterns intentionally narrow.
    #
    # Examples currently present in the Telegram Bot API schema:
    #
    #   It can be one of
    #   It should be one of
    #   Currently, it can be one of
    #   the following 7 scopes are supported:
    #   the following 6 types of chat members are supported:
    #   results of the following 20 types:
    #
    # The actual alternatives are extracted only from known schema names,
    # so ordinary English text cannot create arbitrary union members.
    DESCRIPTION_UNION_PATTERNS = (
        re.compile(
            r"\b(?:it|this\s+object)\s+can\s+be\s+one\s+of\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\b(?:it|this\s+object)\s+should\s+be\s+one\s+of\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\bcan\s+be\s+one\s+of\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\bshould\s+be\s+one\s+of\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\bthe\s+following(?:\s+\d+)?\s+"
            r"(?:types?|scopes?|kinds?)"
            r"(?:\s+of\s+[^:\n]+)?\s+are\s+supported\s*:",
            re.IGNORECASE,
        ),
        re.compile(
            r"\b(?:currently\s+)?support(?:s|ed)?\s+"
            r"(?:results?\s+of\s+)?the\s+following"
            r"(?:\s+\d+)?\s+types?\s*:",
            re.IGNORECASE,
        ),
        re.compile(
            r"\bcurrently\s+support(?:s|ed)?\s+"
            r"(?:results?\s+of\s+)?the\s+following"
            r"(?:\s+\d+)?\s+types?\b",
            re.IGNORECASE,
        ),
    )

    PRIMITIVE_TYPES = {
        "integer": "Integer",
        "string": "String",
        "boolean": "Boolean",
        "number": "Float",
    }

    def __init__(self, document: dict[str, Any]) -> None:
        if not isinstance(document, dict):
            raise TypeError(
                "OpenAPIParser expects an OpenAPI document dictionary"
            )

        self.document = document

        self.components = document.get("components", {})
        if not isinstance(self.components, dict):
            self.components = {}

        self.schemas: dict[str, dict[str, Any]] = self._get_schemas()

        self.description_unions: dict[str, list[str]] = (
            self._discover_description_unions()
        )

        self.openapi_unions: dict[str, list[str]] = (
            self._discover_openapi_unions()
        )

        self.union_registry: dict[str, list[str]] = {}

        for name, alternatives in self.description_unions.items():
            self.union_registry[name] = alternatives

        for name, alternatives in self.openapi_unions.items():
            self.union_registry[name] = alternatives

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def parse(self) -> Schema:
        version = self._extract_version()

        result = Schema(version=version)

        # Parse unions first so that references from object fields and
        # methods can resolve them correctly.
        for name in sorted(self.union_registry):
            alternatives = self.union_registry[name]

            result.unions.append(
                SchemaUnion(
                    name=name,
                    alternatives=list(alternatives),
                    discriminator=None,
                    kind=self._union_schema_kind(name),
                    description=self._schema_description(name),
                )
            )

        # Every schema which is a named union is excluded from the normal
        # object/enum type list.
        for name, schema in self.schemas.items():
            if name in self.union_registry:
                continue

            result.types.append(
                self._parse_type(name, schema)
            )

        result.methods.extend(self._parse_methods())

        return result

    # ------------------------------------------------------------------
    # Union kind
    # ------------------------------------------------------------------

    def _union_schema_kind(self, name: str) -> str:
        """
        Determine the intermediate SchemaUnion kind.

        Telegram's named unions are polymorphic object unions.

        Explicit OpenAPI unions such as value unions are handled separately
        by the existing schema semantics. Description-based Telegram unions
        are always polymorphic because their alternatives are named object
        schemas.
        """
        if name in self.description_unions:
            return "polymorphic"

        return self._infer_openapi_union_kind(name)

    def _infer_openapi_union_kind(self, name: str) -> str:
        """
        Infer the semantic kind of an explicit OpenAPI union.

        Existing tgbotspec-generated unions may already carry useful
        metadata in their description. When no more specific information
        is available, object alternatives are treated as polymorphic.
        """
        alternatives = self.union_registry.get(name, [])

        if not alternatives:
            return "unknown"

        if all(
            self._is_object_schema_name(alternative)
            for alternative in alternatives
        ):
            return "polymorphic"

        return "value"

    def _is_object_schema_name(self, name: str) -> bool:
        schema = self.schemas.get(name)

        if not isinstance(schema, dict):
            return False

        schema_type = schema.get("type")

        if schema_type == "object":
            return True

        if "properties" in schema:
            return True

        if "allOf" in schema:
            return True

        return False

    # ------------------------------------------------------------------
    # OpenAPI document helpers
    # ------------------------------------------------------------------

    def _get_schemas(self) -> dict[str, dict[str, Any]]:
        components = self.document.get("components", {})

        if not isinstance(components, dict):
            return {}

        schemas = components.get("schemas", {})

        if not isinstance(schemas, dict):
            return {}

        result: dict[str, dict[str, Any]] = {}

        for name, schema in schemas.items():
            if not isinstance(name, str):
                continue

            if not isinstance(schema, dict):
                continue

            result[name] = schema

        return result

    def _extract_version(self) -> str:
        info = self.document.get("info", {})

        if not isinstance(info, dict):
            return ""

        version = info.get("version", "")

        if version is None:
            return ""

        return str(version)

    def _schema_description(self, name: str) -> str:
        schema = self.schemas.get(name)

        if not schema:
            return ""

        description = schema.get("description", "")

        if description is None:
            return ""

        return str(description)

    # ------------------------------------------------------------------
    # Union discovery
    # ------------------------------------------------------------------

    def _discover_openapi_unions(self) -> dict[str, list[str]]:
        """
        Discover named unions represented explicitly by oneOf/anyOf.

        A schema is treated as a named union when:

        - it has oneOf or anyOf
        - all alternatives are schema references
        - all references point to known schemas
        - at least two alternatives exist
        """
        unions: dict[str, list[str]] = {}

        for name, schema in self.schemas.items():
            alternatives = self._extract_explicit_union_alternatives(
                schema
            )

            if alternatives:
                unions[name] = alternatives

        return unions

    def _discover_description_unions(self) -> dict[str, list[str]]:
        """
        Discover Telegram unions expressed in schema descriptions.

        Telegram does not consistently encode these relationships with
        OpenAPI oneOf/anyOf. Instead, abstract/base schemas often use prose
        such as:

            It can be one of
            Message
            InaccessibleMessage

        or:

            This object represents the content of a media message to be sent.
            It should be one of
            InputMediaAnimation
            InputMediaAudio
            ...

        or:

            Currently, the following 7 scopes are supported:
            BotCommandScopeDefault
            BotCommandScopeAllPrivateChats
            ...

        Detection is deliberately conservative:

        1. The description must contain a known Telegram union-introduction
           pattern.
        2. Candidate names must be actual component schema names.
        3. Candidate names must refer to object-like schemas.
        4. At least two alternatives must be found.
        5. The owner schema itself is never accepted as an alternative.

        This prevents ordinary empty/object schemas such as StoryArea from
        being classified as unions merely because they happen to have no
        fields.
        """
        unions: dict[str, list[str]] = {}

        for name, schema in self.schemas.items():
            description = schema.get("description", "")

            if not isinstance(description, str):
                continue

            alternatives = (
                self._extract_description_union_alternatives(
                    description,
                    owner=name,
                )
            )

            if len(alternatives) >= 2:
                unions[name] = alternatives

        return unions

    def _extract_explicit_union_alternatives(
        self,
        schema: dict[str, Any],
    ) -> list[str]:
        alternatives: list[str] = []

        for key in ("oneOf", "anyOf"):
            value = schema.get(key)

            if not isinstance(value, list):
                continue

            refs: list[str] = []

            for item in value:
                ref_name = self._extract_ref_name(item)

                if ref_name is None:
                    refs = []
                    break

                if ref_name not in self.schemas:
                    refs = []
                    break

                refs.append(ref_name)

            if len(refs) >= 2:
                alternatives.extend(refs)

        return self._unique_preserving_order(alternatives)

    def _extract_description_union_alternatives(
        self,
        description: str,
        owner: str,
    ) -> list[str]:
        """
        Extract known object-schema names from a Telegram description union.

        The extraction happens after the first recognized union-introduction
        marker. Candidate names are discovered from complete known schema
        names rather than arbitrary words.

        Telegram normally places the alternatives one per line. We therefore
        prefer exact line matches. We also support multiple known schema names
        appearing on the same line, which makes the parser resilient to minor
        formatting changes in future schema versions.
        """
        marker = self._find_description_union_marker(
            description
        )

        if marker is None:
            return []

        suffix = description[
            marker[1]:
        ]

        return self._extract_known_schema_names(
            suffix=suffix,
            owner=owner,
        )

    def _find_description_union_marker(
        self,
        description: str,
    ) -> tuple[int, int] | None:
        """
        Return the (start, end) position of the first recognized Telegram
        union-introduction phrase.

        Matching is case-insensitive and accepts the known wording variants
        used by Telegram's generated schema.
        """
        matches: list[tuple[int, int]] = []

        for pattern in self.DESCRIPTION_UNION_PATTERNS:
            match = pattern.search(description)

            if match is None:
                continue

            matches.append(
                (
                    match.start(),
                    match.end(),
                )
            )

        if not matches:
            return None

        return min(
            matches,
            key=lambda item: (
                item[0],
                item[1],
            ),
        )

    def _extract_known_schema_names(
        self,
        suffix: str,
        owner: str,
    ) -> list[str]:
        """
        Extract known object-schema names from the union suffix.

        Exact line matches are preferred because Telegram normally formats
        description unions as a list:

            InputMediaAnimation
            InputMediaAudio
            InputMediaDocument

        For lines containing multiple names, known schema names are extracted
        in textual order.

        Only object-like schemas are accepted as polymorphic alternatives.
        """
        schema_names = [
            name
            for name in self.schemas
            if name != owner
            and self._is_object_schema_name(name)
        ]

        if not schema_names:
            return []

        schema_names.sort(
            key=lambda item: (
                -len(item),
                item,
            )
        )

        candidates: list[tuple[int, str]] = []

        lines = suffix.splitlines()
        offset = 0

        for raw_line in lines:
            line = raw_line.strip()

            if line:
                exact_name = self._match_exact_schema_name(
                    line,
                    schema_names,
                )

                if exact_name is not None:
                    position = (
                        offset
                        + raw_line.find(exact_name)
                    )

                    candidates.append(
                        (
                            position,
                            exact_name,
                        )
                    )
                else:
                    line_candidates = (
                        self._find_schema_names_in_text(
                            line,
                            schema_names,
                        )
                    )

                    for relative_position, candidate in (
                        line_candidates
                    ):
                        candidates.append(
                            (
                                offset
                                + relative_position,
                                candidate,
                            )
                        )

            offset += len(raw_line) + 1

        candidates.sort(
            key=lambda item: (
                item[0],
                -len(item[1]),
                item[1],
            )
        )

        return self._unique_preserving_order(
            [
                candidate
                for _, candidate in candidates
            ]
        )

    def _match_exact_schema_name(
        self,
        line: str,
        schema_names: list[str],
    ) -> str | None:
        """
        Match a line containing exactly one known schema name.

        Markdown bullets and trailing punctuation are accepted because the
        official documentation and generated schema may use either plain
        lines or bullet-like formatting.
        """
        normalized = line.strip()

        while normalized.startswith((
            "-",
            "*",
            "•",
        )):
            normalized = normalized[1:].strip()

        normalized = normalized.rstrip(
            ".,;:"
        ).strip()

        for candidate in schema_names:
            if normalized == candidate:
                return candidate

        return None

    def _find_schema_names_in_text(
        self,
        text: str,
        schema_names: list[str],
    ) -> list[tuple[int, str]]:
        """
        Find complete known schema names inside one description line.

        Names are matched using identifier boundaries so that:

            InputMediaPhoto

        does not accidentally match inside:

            InputMediaPhotoSomethingElse
        """
        matches: list[tuple[int, str]] = []

        for candidate in schema_names:
            start = 0

            while True:
                position = text.find(
                    candidate,
                    start,
                )

                if position < 0:
                    break

                if self._has_schema_name_boundaries(
                    text,
                    position,
                    candidate,
                ):
                    matches.append(
                        (
                            position,
                            candidate,
                        )
                    )
                    break

                start = position + 1

        matches.sort(
            key=lambda item: (
                item[0],
                -len(item[1]),
                item[1],
            )
        )

        return matches

    @staticmethod
    def _has_schema_name_boundaries(
        text: str,
        position: int,
        name: str,
    ) -> bool:
        before_ok = (
            position == 0
            or not (
                text[position - 1].isalnum()
                or text[position - 1] == "_"
            )
        )

        end = position + len(name)

        after_ok = (
            end == len(text)
            or not (
                text[end].isalnum()
                or text[end] == "_"
            )
        )

        return before_ok and after_ok

    @staticmethod
    def _contains_schema_name(
        text: str,
        name: str,
    ) -> bool:
        """
        Exact whole-name match without relying on a regex.

        Kept as a generic helper because other parser logic may use this
        behavior independently of description-union extraction.
        """
        start = 0

        while True:
            position = text.find(
                name,
                start,
            )

            if position < 0:
                return False

            if OpenAPIParser._has_schema_name_boundaries(
                text,
                position,
                name,
            ):
                return True

            start = position + 1

    @staticmethod
    def _first_name_position(
        text: str,
        name: str,
    ) -> int:
        position = text.find(name)

        if position < 0:
            return 10**9

        return position

    @staticmethod
    def _extract_ref_name(
        value: Any,
    ) -> str | None:
        if not isinstance(value, dict):
            return None

        ref = value.get("$ref")

        if not isinstance(ref, str):
            return None

        if not ref.startswith(
            OpenAPIParser.REF_PREFIX
        ):
            return None

        name = ref[
            len(OpenAPIParser.REF_PREFIX):
        ]

        if not name:
            return None

        return name

    @staticmethod
    def _unique_preserving_order(
        items: list[str],
    ) -> list[str]:
        result: list[str] = []
        seen: set[str] = set()

        for item in items:
            if item in seen:
                continue

            seen.add(item)
            result.append(item)

        return result

    # ------------------------------------------------------------------
    # Schema type parsing
    # ------------------------------------------------------------------

    def _parse_type(
        self,
        name: str,
        schema: dict[str, Any],
    ) -> SchemaType:
        schema_type = schema.get("type")

        if (
            schema_type == "string"
            and "enum" in schema
        ):
            return SchemaType(
                name=name,
                description=self._description(schema),
                fields=[],
                kind="enum",
            )

        if (
            schema_type == "object"
            or "properties" in schema
        ):
            fields = self._parse_object_fields(
                schema
            )

            return SchemaType(
                name=name,
                description=self._description(schema),
                fields=fields,
                kind="object",
            )

        if (
            "properties" in schema
            or "allOf" in schema
            or "additionalProperties" in schema
        ):
            fields = self._parse_object_fields(
                schema
            )

            return SchemaType(
                name=name,
                description=self._description(schema),
                fields=fields,
                kind="object",
            )

        return SchemaType(
            name=name,
            description=self._description(schema),
            fields=[],
            kind="object",
        )

    def _parse_object_fields(
        self,
        schema: dict[str, Any],
    ) -> list[SchemaField]:
        properties = schema.get(
            "properties",
            {},
        )

        if not isinstance(properties, dict):
            properties = {}

        required_values = schema.get(
            "required",
            [],
        )

        if not isinstance(required_values, list):
            required_values = []

        required = {
            str(value)
            for value in required_values
            if isinstance(value, str)
        }

        fields: list[SchemaField] = []

        for name, property_schema in properties.items():
            if not isinstance(name, str):
                continue

            if not isinstance(property_schema, dict):
                property_schema = {}

            fields.append(
                SchemaField(
                    name=name,
                    type=self._schema_type_expression(
                        property_schema
                    ),
                    required=name in required,
                    description=self._description(
                        property_schema
                    ),
                )
            )

        return fields

    def _schema_type_expression(
        self,
        schema: dict[str, Any],
    ) -> str:
        """
        Convert an OpenAPI schema fragment into the intermediate
        Schema type expression.

        Examples:

            {"type": "integer"}
                -> Integer

            {"type": "string"}
                -> String

            {"$ref": "#/components/schemas/User"}
                -> User

            {"type": "array", "items": {"$ref": ".../User"}}
                -> Array<User>

            {"oneOf": [{"$ref": ".../A"}, {"$ref": ".../B"}]}
                -> A or B

            {"allOf": [{"$ref": ".../MaybeInaccessibleMessage"}]}
                -> MaybeInaccessibleMessage
        """
        ref_name = self._extract_ref_name(
            schema
        )

        if ref_name is not None:
            return ref_name

        schema_type = schema.get("type")

        if schema_type in self.PRIMITIVE_TYPES:
            return self.PRIMITIVE_TYPES[schema_type]

        if schema_type == "array":
            items = schema.get("items")

            if not isinstance(items, dict):
                return "Array<Unknown>"

            item_expression = self._schema_type_expression(
                items
            )

            return f"Array<{item_expression}>"

        for key in ("oneOf", "anyOf"):
            value = schema.get(key)

            if isinstance(value, list):
                alternatives: list[str] = []

                for item in value:
                    if not isinstance(item, dict):
                        continue

                    expression = (
                        self._schema_type_expression(
                            item
                        )
                    )

                    if (
                        expression
                        and expression != "Unknown"
                    ):
                        alternatives.append(
                            expression
                        )

                alternatives = (
                    self._unique_preserving_order(
                        alternatives
                    )
                )

                if alternatives:
                    return " or ".join(
                        alternatives
                    )

        all_of = schema.get("allOf")

        if isinstance(all_of, list):
            expressions: list[str] = []

            for item in all_of:
                if not isinstance(item, dict):
                    continue

                expression = (
                    self._schema_type_expression(
                        item
                    )
                )

                if (
                    expression
                    and expression != "Unknown"
                ):
                    expressions.append(
                        expression
                    )

            expressions = (
                self._unique_preserving_order(
                    expressions
                )
            )

            if len(expressions) == 1:
                return expressions[0]

            if len(expressions) > 1:
                return " or ".join(
                    expressions
                )

        if schema_type == "number":
            return "Float"

        return "Unknown"

    # ------------------------------------------------------------------
    # Methods
    # ------------------------------------------------------------------

    def _parse_methods(
        self,
    ) -> list[SchemaMethod]:
        paths = self.document.get(
            "paths",
            {},
        )

        if not isinstance(paths, dict):
            return []

        methods: list[SchemaMethod] = []

        for path, path_item in paths.items():
            if not isinstance(path, str):
                continue

            if not isinstance(path_item, dict):
                continue

            for http_method, operation in path_item.items():
                if http_method.lower() not in {
                    "get",
                    "post",
                    "put",
                    "patch",
                    "delete",
                    "options",
                    "head",
                }:
                    continue

                if not isinstance(operation, dict):
                    continue

                method_name = self._method_name(
                    path,
                    operation,
                )

                if not method_name:
                    continue

                parameters = (
                    self._parse_method_parameters(
                        path_item,
                        operation,
                    )
                )

                return_type = (
                    self._parse_method_return_type(
                        operation
                    )
                )

                methods.append(
                    SchemaMethod(
                        name=method_name,
                        description=self._description(
                            operation
                        ),
                        parameters=parameters,
                        returns=return_type,
                    )
                )

        return methods

    def _method_name(
        self,
        path: str,
        operation: dict[str, Any],
    ) -> str:
        operation_id = operation.get(
            "operationId"
        )

        if (
            isinstance(operation_id, str)
            and operation_id
        ):
            return operation_id

        normalized = (
            path.rstrip("/").split("/")
        )

        if normalized:
            candidate = normalized[-1]

            if candidate:
                return candidate

        return ""

    def _parse_method_parameters(
        self,
        path_item: dict[str, Any],
        operation: dict[str, Any],
    ) -> list[SchemaParameter]:
        parameters: list[SchemaParameter] = []

        inherited = path_item.get(
            "parameters",
            []
        )

        if isinstance(inherited, list):
            parameters.extend(
                self._parse_parameter_list(
                    inherited
                )
            )

        operation_parameters = operation.get(
            "parameters",
            []
        )

        if isinstance(operation_parameters, list):
            parameters.extend(
                self._parse_parameter_list(
                    operation_parameters
                )
            )

        request_body = operation.get(
            "requestBody"
        )

        if isinstance(request_body, dict):
            parameters.extend(
                self._parse_request_body_parameters(
                    request_body
                )
            )

        return self._deduplicate_parameters(
            parameters
        )

    def _parse_parameter_list(
        self,
        parameters: list[Any],
    ) -> list[SchemaParameter]:
        result: list[SchemaParameter] = []

        for parameter in parameters:
            if not isinstance(parameter, dict):
                continue

            ref_name = self._extract_ref_name(
                parameter
            )

            if ref_name is not None:
                continue

            name = parameter.get("name")

            if (
                not isinstance(name, str)
                or not name
            ):
                continue

            schema = parameter.get(
                "schema",
                {},
            )

            if not isinstance(schema, dict):
                schema = {}

            result.append(
                SchemaParameter(
                    name=name,
                    type=self._schema_type_expression(
                        schema
                    ),
                    required=bool(
                        parameter.get(
                            "required",
                            False,
                        )
                    ),
                    description=self._description(
                        parameter
                    ),
                )
            )

        return result

    def _parse_request_body_parameters(
        self,
        request_body: dict[str, Any],
    ) -> list[SchemaParameter]:
        content = request_body.get(
            "content"
        )

        if not isinstance(content, dict):
            return []

        # When both JSON and multipart are provided, JSON is the semantic
        # source of truth for structured parameters (arrays/objects), while
        # multipart is the source of truth for file-upload representations.
        # Selecting multipart wholesale turns fields such as
        # caption_entities and suggested_post_parameters into strings.
        json_media = content.get("application/json")
        multipart_media = content.get("multipart/form-data")

        if isinstance(json_media, dict):
            json_schema = json_media.get("schema")
            if isinstance(json_schema, dict) and (
                json_schema.get("type") == "object"
                or "properties" in json_schema
            ):
                parameters = self._parse_object_parameters(json_schema)

                if isinstance(multipart_media, dict):
                    multipart_schema = multipart_media.get("schema")
                    if isinstance(multipart_schema, dict) and (
                        multipart_schema.get("type") == "object"
                        or "properties" in multipart_schema
                    ):
                        multipart_properties = multipart_schema.get("properties", {})
                        if isinstance(multipart_properties, dict):
                            for parameter in parameters:
                                multipart_property = multipart_properties.get(parameter.name)
                                if not isinstance(multipart_property, dict):
                                    continue

                                multipart_expression = self._schema_type_expression(
                                    multipart_property
                                )
                                if "InputFile" in multipart_expression:
                                    parameter.type = multipart_expression

                return parameters

        # Fall back to the normal media-type selection for operations that
        # expose only one request representation.
        media_type = self._select_request_media_type(content)
        if media_type is None:
            return []

        media = content.get(media_type)
        if not isinstance(media, dict):
            return []

        schema = media.get("schema")
        if not isinstance(schema, dict):
            return []

        if schema.get("type") == "object" or "properties" in schema:
            return self._parse_object_parameters(schema)

        ref_name = self._extract_ref_name(schema)
        if ref_name is not None:
            return [SchemaParameter(
                name="request",
                type=ref_name,
                required=True,
                description=self._description(request_body),
            )]

        return [SchemaParameter(
            name="request",
            type=self._schema_type_expression(schema),
            required=True,
            description=self._description(request_body),
        )]

    @staticmethod
    def _select_request_media_type(
        content: dict[str, Any],
    ) -> str | None:
        """
        Select the request-body media type used to derive Telegram method
        parameters.

        Telegram Bot API methods may expose both:

            application/json
            multipart/form-data

        for the same operation.

        For parameter-model generation, multipart/form-data is authoritative
        when present because it preserves file-upload semantics such as:

            InputFile | String

        Selection priority:

            1. multipart/form-data
            2. application/json
            3. application/x-www-form-urlencoded
            4. first available media type
        """
        preferred = [
            "multipart/form-data",
            "application/json",
            "application/x-www-form-urlencoded",
        ]

        for media_type in preferred:
            if media_type in content:
                return media_type

        for media_type in content:
            return media_type

        return None

    def _parse_object_parameters(
        self,
        schema: dict[str, Any],
    ) -> list[SchemaParameter]:
        properties = schema.get(
            "properties",
            {},
        )

        if not isinstance(properties, dict):
            properties = {}

        required_values = schema.get(
            "required",
            [],
        )

        if not isinstance(required_values, list):
            required_values = []

        required = {
            str(value)
            for value in required_values
            if isinstance(value, str)
        }

        result: list[SchemaParameter] = []

        for name, property_schema in properties.items():
            if not isinstance(name, str):
                continue

            if not isinstance(property_schema, dict):
                property_schema = {}

            result.append(
                SchemaParameter(
                    name=name,
                    type=self._schema_type_expression(
                        property_schema
                    ),
                    required=name in required,
                    description=self._description(
                        property_schema
                    ),
                )
            )

        return result

    def _deduplicate_parameters(
        self,
        parameters: list[SchemaParameter],
    ) -> list[SchemaParameter]:
        result: list[SchemaParameter] = []
        seen: set[str] = set()

        for parameter in parameters:
            if parameter.name in seen:
                continue

            seen.add(parameter.name)
            result.append(parameter)

        return result

    # ------------------------------------------------------------------
    # Responses
    # ------------------------------------------------------------------

    def _parse_method_return_type(
        self,
        operation: dict[str, Any],
    ) -> str:
        responses = operation.get(
            "responses"
        )

        if not isinstance(responses, dict):
            return "Unknown"

        response = responses.get("200")

        if response is None:
            for status, candidate in responses.items():
                if str(status).startswith("2"):
                    response = candidate
                    break

        if not isinstance(response, dict):
            return "Unknown"

        content = response.get(
            "content"
        )

        if not isinstance(content, dict):
            return "Unknown"

        media = self._select_response_media(
            content
        )

        if media is None:
            return "Unknown"

        schema = media.get("schema")

        if not isinstance(schema, dict):
            return "Unknown"

        result_schema = (
            self._extract_result_schema(
                schema
            )
        )

        if result_schema is None:
            return "Unknown"

        return self._schema_type_expression(
            result_schema
        )

    @staticmethod
    def _select_response_media(
        content: dict[str, Any],
    ) -> dict[str, Any] | None:
        preferred = [
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data",
        ]

        for media_type in preferred:
            media = content.get(
                media_type
            )

            if isinstance(media, dict):
                return media

        for media in content.values():
            if isinstance(media, dict):
                return media

        return None

    def _extract_result_schema(
        self,
        schema: dict[str, Any],
    ) -> dict[str, Any] | None:
        properties = schema.get(
            "properties"
        )

        if isinstance(properties, dict):
            result = properties.get(
                "result"
            )

            if isinstance(result, dict):
                return result

        all_of = schema.get(
            "allOf"
        )

        if isinstance(all_of, list):
            for item in all_of:
                if not isinstance(item, dict):
                    continue

                result = (
                    self._extract_result_schema(
                        item
                    )
                )

                if result is not None:
                    return result

        return None

    # ------------------------------------------------------------------
    # Generic helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _description(
        value: dict[str, Any],
    ) -> str:
        description = value.get(
            "description",
            ""
        )

        if description is None:
            return ""

        return str(description)


def parse_openapi(
    document: dict[str, Any],
) -> Schema:
    """
    Compatibility helper for callers which prefer a module-level function.
    """
    return OpenAPIParser(document).parse()
