from __future__ import annotations

from Model import (
    TelegramModel,
    TelegramType,
    TypeKind,
)

from CppContext import CppContext


class SerializerGenerator:
    """
    Generate a standalone Boost.JSON serializer.

    Runtime representation:

        primitive
        std::optional<T>
        std::shared_ptr<T>
        std::vector<T>
        std::variant<...>
        InputFile
        Telegram object

    Named unions are generated by TypeGenerator as std::variant aliases.
    They therefore use the generic std::variant JsonConverter and do not
    receive explicit Serializer specializations.
    """

    def __init__(
        self,
        model: TelegramModel,
        context: CppContext,
    ) -> None:
        self.model = model
        self.context = context

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self) -> str:

        lines: list[str] = []

        lines.extend(
            self._render_header()
        )

        lines.extend(
            self._render_includes()
        )

        lines.append(
            "namespace TelegramBotAPI::JSON {"
        )
        lines.append("")

        lines.extend(
            self._render_json_aliases()
        )

        lines.append("namespace Detail {")
        lines.append("")

        lines.extend(
            self._render_runtime_templates()
        )

        lines.extend(
            self._render_serializer_declarations()
        )

        lines.extend(
            self._render_serializer_definitions()
        )

        lines.append("} // namespace Detail")
        lines.append("")
        lines.extend(
            self._render_to_json()
        )

        lines.append(
            "} // namespace TelegramBotAPI::JSON"
        )
        lines.append("")

        lines.extend(
            self._render_footer()
        )

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Header / footer
    # ------------------------------------------------------------------

    def _render_header(self) -> list[str]:

        return [
            "#ifndef TELEGRAMBOTAPI_GENERATED_SERIALIZER_HPP",
            "#define TELEGRAMBOTAPI_GENERATED_SERIALIZER_HPP",
            "",
        ]

    def _render_footer(self) -> list[str]:

        return [
            "#endif // TELEGRAMBOTAPI_GENERATED_SERIALIZER_HPP",
            "",
        ]

    # ------------------------------------------------------------------
    # Includes
    # ------------------------------------------------------------------

    def _render_includes(self) -> list[str]:

        includes: set[str] = {
            "<boost/json.hpp>",
            "<cstdint>",
            "<memory>",
            "<optional>",
            "<string>",
            "<type_traits>",
            "<utility>",
            "<variant>",
            "<vector>",
            '"TelegramBotAPI/JSON/Json.HPP"',
        }

        includes.add(
            '"TelegramBotAPI/Types/InputFile.HPP"'
        )

        for item in self.model.types:

            includes.add(
                f'"TelegramBotAPI/Types/{item.name}.HPP"'
            )

        for union in self.model.unions:

            includes.add(
                f'"TelegramBotAPI/Types/{union.name}.HPP"'
            )

        lines = [
            f"#include {include}"
            for include in sorted(includes)
        ]

        lines.append("")

        return lines

    # ------------------------------------------------------------------
    # JSON aliases
    # ------------------------------------------------------------------

    def _render_json_aliases(self) -> list[str]:

        return [
            "using Value = boost::json::value;",
            "using Object = boost::json::object;",
            "using Array = boost::json::array;",
            "",
        ]

    # ------------------------------------------------------------------
    # Runtime templates
    # ------------------------------------------------------------------

    def _render_runtime_templates(self) -> list[str]:

        lines: list[str] = []

        lines.extend(
            self._render_serializer_primary()
        )

        lines.extend(
            self._render_json_converter_primary()
        )

        lines.extend(
            self._render_boost_json_value_converter()
        )

        lines.extend(
            self._render_primitive_converters()
        )

        lines.extend(
            self._render_optional_converter()
        )

        lines.extend(
            self._render_shared_ptr_converter()
        )

        lines.extend(
            self._render_vector_converter()
        )

        lines.extend(
            self._render_variant_converter()
        )

        lines.extend(
            self._render_input_file_converter()
        )

        lines.extend(
            self._render_set_field_helpers()
        )

        return lines

    # ------------------------------------------------------------------
    # Serializer primary
    # ------------------------------------------------------------------

    def _render_serializer_primary(self) -> list[str]:

        return [
            "template <typename Type>",
            "struct Serializer;",
            "",
        ]

    # ------------------------------------------------------------------
    # Generic JsonConverter
    # ------------------------------------------------------------------

    def _render_json_converter_primary(self) -> list[str]:

        return [
            "template <typename Type>",
            "struct JsonConverter {",
            "",
            "    static Value Convert(",
            "        const Type &ObjectValue) {",
            "",
            "        return Serializer<Type>::Serialize(",
            "            ObjectValue);",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # boost::json::value passthrough
    # ------------------------------------------------------------------

    def _render_boost_json_value_converter(self) -> list[str]:

        return [
            "template <>",
            "struct JsonConverter<boost::json::value> {",
            "",
            "    static Value Convert(",
            "        const boost::json::value &ObjectValue) {",
            "        return ObjectValue;",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # Primitive converters
    # ------------------------------------------------------------------

    def _render_primitive_converters(self) -> list[str]:

        return [
            "template <>",
            "struct JsonConverter<bool> {",
            "",
            "    static Value Convert(",
            "        const bool &ObjectValue) {",
            "        return Value(ObjectValue);",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<short> {",
            "",
            "    static Value Convert(",
            "        const short &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::int64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<unsigned short> {",
            "",
            "    static Value Convert(",
            "        const unsigned short &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::uint64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<int> {",
            "",
            "    static Value Convert(",
            "        const int &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::int64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<unsigned int> {",
            "",
            "    static Value Convert(",
            "        const unsigned int &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::uint64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<long> {",
            "",
            "    static Value Convert(",
            "        const long &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::int64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<unsigned long> {",
            "",
            "    static Value Convert(",
            "        const unsigned long &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::uint64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<long long> {",
            "",
            "    static Value Convert(",
            "        const long long &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::int64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<unsigned long long> {",
            "",
            "    static Value Convert(",
            "        const unsigned long long &ObjectValue) {",
            "        return Value(",
            "            static_cast<std::uint64_t>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<float> {",
            "",
            "    static Value Convert(",
            "        const float &ObjectValue) {",
            "        return Value(",
            "            static_cast<double>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<double> {",
            "",
            "    static Value Convert(",
            "        const double &ObjectValue) {",
            "        return Value(ObjectValue);",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<long double> {",
            "",
            "    static Value Convert(",
            "        const long double &ObjectValue) {",
            "        return Value(",
            "            static_cast<double>(ObjectValue));",
            "    }",
            "};",
            "",

            "template <>",
            "struct JsonConverter<std::string> {",
            "",
            "    static Value Convert(",
            "        const std::string &ObjectValue) {",
            "        return Value(ObjectValue);",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # Optional
    # ------------------------------------------------------------------

    def _render_optional_converter(self) -> list[str]:

        return [
            "template <typename Type>",
            "struct JsonConverter<std::optional<Type>> {",
            "",
            "    static Value Convert(",
            "        const std::optional<Type> &ObjectValue) {",
            "",
            "        if (!ObjectValue.has_value()) {",
            "            return Value(nullptr);",
            "        }",
            "",
            "        return JsonConverter<Type>::Convert(",
            "            ObjectValue.value());",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # shared_ptr
    # ------------------------------------------------------------------

    def _render_shared_ptr_converter(self) -> list[str]:

        return [
            "template <typename Type>",
            "struct JsonConverter<std::shared_ptr<Type>> {",
            "",
            "    static Value Convert(",
            "        const std::shared_ptr<Type> &ObjectValue) {",
            "",
            "        if (!ObjectValue) {",
            "            return Value(nullptr);",
            "        }",
            "",
            "        return JsonConverter<Type>::Convert(",
            "            *ObjectValue);",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # vector
    # ------------------------------------------------------------------

    def _render_vector_converter(self) -> list[str]:

        return [
            "template <typename Type>",
            "struct JsonConverter<std::vector<Type>> {",
            "",
            "    static Value Convert(",
            "        const std::vector<Type> &ObjectValue) {",
            "",
            "        Array JsonArray;",
            "        JsonArray.reserve(ObjectValue.size());",
            "",
            "        for (const Type &Element : ObjectValue) {",
            "            JsonArray.push_back(",
            "                JsonConverter<Type>::Convert(Element));",
            "        }",
            "",
            "        return Value(std::move(JsonArray));",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # variant
    # ------------------------------------------------------------------

    def _render_variant_converter(self) -> list[str]:

        return [
            "template <typename... Types>",
            "struct JsonConverter<std::variant<Types...>> {",
            "",
            "    static Value Convert(",
            "        const std::variant<Types...> &ObjectValue) {",
            "",
            "        return std::visit(",
            "            [](const auto &Alternative) -> Value {",
            "",
            "                using AlternativeType =",
            "                    std::decay_t<decltype(Alternative)>;",
            "",
            "                return JsonConverter<AlternativeType>::Convert(",
            "                    Alternative);",
            "            },",
            "            ObjectValue);",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # InputFile
    # ------------------------------------------------------------------

    def _render_input_file_converter(self) -> list[str]:

        return [
            "template <>",
            "struct JsonConverter<",
            "    ::TelegramBotAPI::Type::InputFile> {",
            "",
            "    static Value Convert(",
            "        const ::TelegramBotAPI::Type::InputFile &ObjectValue) {",
            "",
            "        return Value(ObjectValue.GetValue());",
            "    }",
            "};",
            "",
        ]

    # ------------------------------------------------------------------
    # Field helpers
    # ------------------------------------------------------------------

    def _render_set_field_helpers(self) -> list[str]:

        return [
            "template <typename Type>",
            "void SetField(",
            "    Object &JsonObject,",
            "    const char *FieldName,",
            "    const Type &FieldValue) {",
            "",
            "    using CleanType =",
            "        std::remove_cv_t<std::remove_reference_t<Type>>;",
            "",
            "    JsonObject[FieldName] =",
            "        JsonConverter<CleanType>::Convert(FieldValue);",
            "}",
            "",

            "template <typename Type>",
            "void SetOptionalField(",
            "    Object &JsonObject,",
            "    const char *FieldName,",
            "    const std::optional<Type> &FieldValue) {",
            "",
            "    if (!FieldValue.has_value()) {",
            "        return;",
            "    }",
            "",
            "    SetField(",
            "        JsonObject,",
            "        FieldName,",
            "        FieldValue.value());",
            "}",
            "",

            "template <typename Type>",
            "void SetSharedPtrField(",
            "    Object &JsonObject,",
            "    const char *FieldName,",
            "    const std::shared_ptr<Type> &FieldValue) {",
            "",
            "    if (!FieldValue) {",
            "        return;",
            "    }",
            "",
            "    SetField(",
            "        JsonObject,",
            "        FieldName,",
            "        *FieldValue);",
            "}",
            "",
        ]

    # ------------------------------------------------------------------
    # Serializer declarations
    # ------------------------------------------------------------------

    def _render_serializer_declarations(self) -> list[str]:

        lines: list[str] = []

        for item in self.model.types:

            if item.kind != TypeKind.OBJECT:
                continue

            lines.extend([
                "template <>",
                (
                    "struct Serializer<"
                    "::TelegramBotAPI::Type::"
                    f"{item.name}>;"
                ),
                "",
            ])

        return lines

    # ------------------------------------------------------------------
    # Serializer definitions
    # ------------------------------------------------------------------

    def _render_serializer_definitions(self) -> list[str]:

        lines: list[str] = []

        for item in self.model.types:

            if item.kind == TypeKind.OBJECT:

                lines.extend(
                    self._render_object_serializer(
                        item
                    )
                )

            elif item.kind == TypeKind.ENUM:

                lines.extend(
                    self._render_enum_serializer(
                        item
                    )
                )

        return lines

    # ------------------------------------------------------------------
    # Object serializer
    # ------------------------------------------------------------------

    def _render_object_serializer(
        self,
        item: TelegramType,
    ) -> list[str]:

        lines = [
            "template <>",
            (
                "struct Serializer<"
                "::TelegramBotAPI::Type::"
                f"{item.name}> {{"
            ),
            "",
            "    static Value Serialize(",
            (
                "        const "
                "::TelegramBotAPI::Type::"
                f"{item.name}"
                " &ObjectValue) {"
            ),
            "",
            "        Object JsonObject;",
            "",
        ]

        for field in item.fields:

            lines.extend(
                self._render_field_serialization(
                    owner=item.name,
                    field=field,
                )
            )

        lines.extend([
            "        return Value(std::move(JsonObject));",
            "    }",
            "};",
            "",
        ])

        return lines

    # ------------------------------------------------------------------
    # Enum
    # ------------------------------------------------------------------

    def _render_enum_serializer(
        self,
        item: TelegramType,
    ) -> list[str]:

        raise NotImplementedError(
            "Enum serializer generation is not implemented yet: "
            f"{item.name}"
        )

    # ------------------------------------------------------------------
    # Field serialization
    # ------------------------------------------------------------------

    def _render_field_serialization(
        self,
        owner: str,
        field,
    ) -> list[str]:

        # --------------------------------------------------------------
        # Required field
        # --------------------------------------------------------------

        if field.required:

            return [
                "        SetField(",
                f'            JsonObject, "{field.name}",',
                (
                    f"            ObjectValue."
                    f"{field.cpp_name});"
                ),
                "",
            ]

        # --------------------------------------------------------------
        # Optional field
        # --------------------------------------------------------------

        #
        # IMPORTANT:
        #
        # We determine the outer wrapper from the schema/model,
        # not from the final C++ type string.
        #
        # This prevents:
        #
        #     optional<shared_ptr<T>>
        #
        # from accidentally being dispatched to SetSharedPtrField.
        #

        if field.type.is_union():

            cpp_type = self.context.field_type_to_cpp(
                field.type,
                required=False,
                owner=owner,
            )

            if cpp_type.type.startswith(
                "std::optional<"
            ):

                return [
                    "        SetOptionalField(",
                    (
                        f'            JsonObject, '
                        f'"{field.name}",'
                    ),
                    (
                        f"            ObjectValue."
                        f"{field.cpp_name});"
                    ),
                    "",
                ]

        if field.type.is_object():

            cpp_type = self.context.field_type_to_cpp(
                field.type,
                required=False,
                owner=owner,
            )

            if cpp_type.type.startswith(
                "std::shared_ptr<"
            ):

                return [
                    "        SetSharedPtrField(",
                    (
                        f'            JsonObject, '
                        f'"{field.name}",'
                    ),
                    (
                        f"            ObjectValue."
                        f"{field.cpp_name});"
                    ),
                    "",
                ]

        #
        # All other non-required fields are std::optional<T>.
        #

        cpp_type = self.context.field_type_to_cpp(
            field.type,
            required=False,
            owner=owner,
        )

        if cpp_type.type.startswith(
            "std::optional<"
        ):

            return [
                "        SetOptionalField(",
                (
                    f'            JsonObject, '
                    f'"{field.name}",'
                ),
                (
                    f"            ObjectValue."
                    f"{field.cpp_name});"
                ),
                "",
            ]

        # --------------------------------------------------------------
        # Fallback
        # --------------------------------------------------------------

        return [
            "        SetField(",
            (
                f'            JsonObject, '
                f'"{field.name}",'
            ),
            (
                f"            ObjectValue."
                f"{field.cpp_name});"
            ),
            "",
        ]

    # ------------------------------------------------------------------
    # ToJson
    # ------------------------------------------------------------------

    def _render_to_json(self) -> list[str]:

        return [
            "template <typename Type>",
            "Value ToJson(",
            "    const Type &ObjectValue) {",
            "",
            "    using CleanType =",
            "        std::remove_cv_t<std::remove_reference_t<Type>>;",
            "",
            "    return Detail::JsonConverter<CleanType>::Convert(",
            "        ObjectValue);",
            "}",
            "",
        ]
